name:                oeis2
version:             0.1.0.0
github:              "23_prime/oeis2"
license:             BSD3
author:              "okkey"
maintainer:          "a23b23c23d23e@gmail.com"
copyright:           "2018 okkey"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Interface for Online Encyclopedia of Integer Sequences (OEIS).
category:            Math

description:         Please see the README on GitHub at <https://github.com/23_prime/oeis2#readme>

dependencies:
- base >= 4.7 && < 5
- HTTP
- aeson
- containers
- lens
- lens-aeson
- text
- hspec

library:
  source-dirs: src

tests:
  oeis2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oeis2
    - hspec
