name:                oeis2
version:             1.0.0
github:              "23prime/oeis2"
license:             BSD3
author:              "Taisuke Hikawa"
maintainer:          "a23b23c23d23e@gmail.com"
copyright:           "2018 Taisuke Hikawa"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Interface for Online Encyclopedia of Integer Sequences (OEIS).
category:            Math

description:         Please see the README on GitHub at <https://github.com/23prime/oeis2#readme>

dependencies:
- base         >= 4.7  && < 5
- text         >= 1.2  && < 1.3
- vector       >= 0.12 && < 0.13
- aeson        >= 1.3  && < 1.5
- containers   >= 0.5  && < 0.7
- lens         >= 4.16 && < 4.18
- lens-aeson   >= 1.0  && < 1.1
- http-conduit >= 2.3  && < 2.4
# - hspec
# - QuickCheck

library:
  source-dirs: src

tests:
  oeis2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oeis2
    - hspec
    - QuickCheck
