name:                oeis2
version:             0.1.0.0
github:              "23_prime/oeis2"
license:             BSD3
author:              "okkey"
maintainer:          "example@example.com"
copyright:           "2018 okkey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/23_prime/oeis2#readme>

dependencies:
- base >= 4.7 && < 5
- HTTP
- aeson
- containers
- lens
- lens-aeson
- text

library:
  source-dirs: src