# c.f.)
## GitHub Actions
# - https://github.com/haskell/actions/tree/main/setup
# - https://debug-ito.hatenablog.com/entry/2021/02/28/121631
# - https://stackoverflow.com/questions/68399221/github-actions-for-testing-haskell-package

## Versions
# - https://www.haskell.org/ghc/
# - https://www.stackage.org

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "!**.md"
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - "!**.md"

name: build

jobs:
  test:
    name: Stack Test

    strategy:
      fail-fast: false
      matrix:
        plan:
          - ghc: 9.4.8
            resolver: lts-21.25
          - ghc: 9.6.5
            resolver: lts-22.25
          - ghc: 9.8.2
            resolver: nightly
          - ghc: latest
            resolver: lts
          # Now, 'ghc: head' is unable
          # See: https://github.com/haskell/actions/issues/93
          # - ghc: head

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.plan.allow-fail == true }}
    env:
      STACK: stack --no-terminal --system-ghc --resolver ${{ matrix.plan.resolver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.plan.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.plan.resolver }}

      - name: Versions
        run: |
          ghc --version
          stack --version

      - name: Configure
        run: |
          set -ex
          rm -f stack.yaml.lock
          $STACK clean

      - name: Install dependencies
        run: $STACK test --only-dependencies

      - name: Build
        run: $STACK build

      - name: Test
        run: $STACK test
